project:
  type: website
  output-dir: "."

website:
  title: "Projeto Finanças"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre
      - href: appdash.qmd
        text: Dashboard
      - href: page2.qmd
        text: Logs de Retorno
      - href: page3.qmd
        text: Futuro
      - href: fuzzy_topsis_analise_acoes.qmd
        text: Fuzzy Topsis
      - href: page4.qmd
        text: Forecasting
      - href: analise_acoes_gerado.qmd
        text: Análise de Ações
    right:
      - icon: github
        href: "https://github.com/FinancasFae"
        aria-label: "GitHub"
  sidebar:
    style: "floating" 
    search: true  

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-location: left  
    page-layout: article  

execute:
  engine: python
  python: "C:/Users/kuiav/anaconda3/python.exe"
