project:
  type: website
  output-dir: "."
website:
  title: "Projeto Finanças"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre  
      - href: page3.qmd
        text: Logs de Retorno
      - href: page2.qmd
        text: Futuro
    right:
      - icon: github
        href: "https://github.com/FinancasFae"
        aria-label: "GitHub"
  sidebar:
    style: "floating" 
    search: true  

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-location: left  
    page-layout: article  



