---
title: "Projeto Finanças"
format:
  html:
    self-contained: true
    toc: true
    code-fold: true
    df-print: paged
editor: visual
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = NA
)
knitr::opts_chunk$set(comment = NA)    # Remove all coments # of R outputs
knitr::opts_chunk$set(warning = FALSE) # Remove all warnings # of R outputs
knitr::opts_chunk$set(message = FALSE) # Remove all messages # of R outputs
```

Análise das séries Temporais de preços de nossas ações:

```{# Gráfico de linha interativo com plotly}
fig <- plot_ly(portfolio_prices_long,
               x = ~date,
               y = ~Valor,
               color = ~Ativo,
               type = 'scatter',
               mode = 'lines') %>%
  layout(title = "Séries Temporais de Preços",
         xaxis = list(title = "Data"),
         yaxis = list(title = "Valor"))

fig
```

```{r fig.width=9, fig.height=9} # Visualizar com DT datatable(tail(portfolioPrices), options = list(pageLength = 10, scrollX = TRUE))}
```

E então a gente faz uma analise temporal dos dados, tendo o eixo X sendo a variável tempo, e o eixo Y sendo o preço:

```{r} portfolioPrices |> as.data.frame() |>   mutate(     time = seq_along(GIS)   ) |>   pivot_longer(     !time,     names_to = "Variables",     values_to = "Value"     ) |>   group_by(Variables) |>   plot_time_series(     time,     Value,     .interactive = F, # Change for TRUE for better visualization     .facet_ncol = 2,     .smooth = FALSE   ) +   theme(     strip.background = element_rect(fill = "white", colour = "white")   )}
```
